<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.8" />
    <PackageReference Include="Microsoft.OpenApi" Version="2.7.5" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.14.14" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Librory.Application\Librory.Application.csproj" />
    <ProjectReference Include="..\Librory.Infrastructure\Librory.Infrastructure.csproj" />
    <ProjectReference Include="..\Librory.ServiceDefaults\Librory.ServiceDefaults.csproj" />
  </ItemGroup>
</Project>
