// <auto-generated />
using System;
using Librory.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Librory.Infrastructure.Migrations
{
    [DbContext(typeof(LibroryDbContext))]
    partial class LibroryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Librory.Domain.Models.BookCopy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookEditionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Condition")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("PurchasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("PurchaseStore")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("PurchasedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ShelfLocation")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("BookEditionId");

                    b.HasIndex("FamilyId");

                    b.HasIndex("MemberId");

                    b.ToTable("BookCopies");
                });

            modelBuilder.Entity("Librory.Domain.Models.BookEdition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookWorkId")
                        .HasColumnType("uuid");

                    b.Property<string>("Format")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Isbn")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("PublicationYear")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BookWorkId");

                    b.ToTable("BookEditions");
                });

            modelBuilder.Entity("Librory.Domain.Models.BookWork", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CanonicalAuthor")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("CanonicalTitle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("BookWorks");
                });

            modelBuilder.Entity("Librory.Domain.Models.Family", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Families");
                });

            modelBuilder.Entity("Librory.Domain.Models.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("Librory.Domain.Models.RecommendationProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FamilyId")
                        .HasColumnType("uuid");

                    b.Property<string>("FavoriteAuthors")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FavoriteGenres")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FavoriteStyles")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("MaximumAge")
                        .HasColumnType("integer");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<int?>("MinimumAge")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.HasIndex("MemberId")
                        .IsUnique();

                    b.ToTable("RecommendationProfile");
                });

            modelBuilder.Entity("Librory.Domain.Models.ScanSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.ToTable("ScanSessions");
                });

            modelBuilder.Entity("Librory.Domain.Models.WishlistItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Author")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("BookEditionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BookWorkId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("BookEditionId");

                    b.HasIndex("BookWorkId");

                    b.HasIndex("FamilyId");

                    b.ToTable("WishlistItems");
                });

            modelBuilder.Entity("Librory.Domain.Models.BookCopy", b =>
                {
                    b.HasOne("Librory.Domain.Models.BookEdition", "BookEdition")
                        .WithMany("Copies")
                        .HasForeignKey("BookEditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Librory.Domain.Models.Family", "Family")
                        .WithMany("BookCopies")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Librory.Domain.Models.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookEdition");

                    b.Navigation("Family");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Librory.Domain.Models.BookEdition", b =>
                {
                    b.HasOne("Librory.Domain.Models.BookWork", "BookWork")
                        .WithMany("Editions")
                        .HasForeignKey("BookWorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookWork");
                });

            modelBuilder.Entity("Librory.Domain.Models.BookWork", b =>
                {
                    b.OwnsOne("Librory.Domain.Models.LocalizedText", "Summary", b1 =>
                        {
                            b1.Property<Guid>("BookWorkId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Chinese")
                                .HasMaxLength(4000)
                                .HasColumnType("character varying(4000)");

                            b1.Property<string>("English")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("character varying(4000)");

                            b1.HasKey("BookWorkId");

                            b1.ToTable("BookWorks");

                            b1.WithOwner()
                                .HasForeignKey("BookWorkId");
                        });

                    b.Navigation("Summary");
                });

            modelBuilder.Entity("Librory.Domain.Models.Member", b =>
                {
                    b.HasOne("Librory.Domain.Models.Family", "Family")
                        .WithMany("Members")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Family");
                });

            modelBuilder.Entity("Librory.Domain.Models.RecommendationProfile", b =>
                {
                    b.HasOne("Librory.Domain.Models.Family", null)
                        .WithMany("RecommendationProfiles")
                        .HasForeignKey("FamilyId");

                    b.HasOne("Librory.Domain.Models.Member", "Member")
                        .WithOne("RecommendationProfile")
                        .HasForeignKey("Librory.Domain.Models.RecommendationProfile", "MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Librory.Domain.Models.ScanSession", b =>
                {
                    b.HasOne("Librory.Domain.Models.Family", "Family")
                        .WithMany("ScanSessions")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Family");
                });

            modelBuilder.Entity("Librory.Domain.Models.WishlistItem", b =>
                {
                    b.HasOne("Librory.Domain.Models.BookEdition", "BookEdition")
                        .WithMany()
                        .HasForeignKey("BookEditionId");

                    b.HasOne("Librory.Domain.Models.BookWork", "BookWork")
                        .WithMany()
                        .HasForeignKey("BookWorkId");

                    b.HasOne("Librory.Domain.Models.Family", "Family")
                        .WithMany("WishlistItems")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookEdition");

                    b.Navigation("BookWork");

                    b.Navigation("Family");
                });

            modelBuilder.Entity("Librory.Domain.Models.BookEdition", b =>
                {
                    b.Navigation("Copies");
                });

            modelBuilder.Entity("Librory.Domain.Models.BookWork", b =>
                {
                    b.Navigation("Editions");
                });

            modelBuilder.Entity("Librory.Domain.Models.Family", b =>
                {
                    b.Navigation("BookCopies");

                    b.Navigation("Members");

                    b.Navigation("RecommendationProfiles");

                    b.Navigation("ScanSessions");

                    b.Navigation("WishlistItems");
                });

            modelBuilder.Entity("Librory.Domain.Models.Member", b =>
                {
                    b.Navigation("RecommendationProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
