import type { ThemeDefinition, ThemeName } from './themeTypes'

export const themeStorageKey = 'librory.theme'
export const defaultThemeName: ThemeName = 'botanical-press'

export const themeOrder: ThemeName[] = ['botanical-press', 'classic-scholar', 'modern-scout', 'cozy-archive']

export const themeRegistry: Record<ThemeName, ThemeDefinition> = {
  'classic-scholar': {
    label: 'Classic Scholar',
    tokens: {
      pageBg: '#f8f4ee',
      surfaceElevated: '#fffdf9',
      surfaceSunken: '#f0e8df',
      borderSubtle: '#d7c7b7',
      borderStrong: '#b8aa9c',
      textPrimary: '#201915',
      textSecondary: '#61544d',
      textTertiary: '#95877f',
      accent: '#a66a2c',
      accentOnAccent: '#ffffff',
      accentSubtle: 'rgba(166, 106, 44, 0.12)',
      accentMuted: 'rgba(166, 106, 44, 0.06)',
      statusRecommend: '#4c7a57',
      statusWarn: '#9b6a2f',
      statusAlert: '#a75d52',
      statusNeutral: '#988b84',
      shadow1: 'none',
      shadow2: '0 8px 22px rgba(40, 30, 20, 0.07)',
      shadow3: '0 16px 36px rgba(40, 30, 20, 0.12)',
      fontBody: '"Inter", system-ui, sans-serif',
      fontDisplay: '"Instrument Serif", Georgia, serif',
      fontMono: '"Inter", ui-monospace, monospace',
    },
  },
  'modern-scout': {
    label: 'Modern Scout',
    tokens: {
      pageBg: '#f6f8fb',
      surfaceElevated: '#ffffff',
      surfaceSunken: '#edf2f7',
      borderSubtle: '#d8e0ea',
      borderStrong: '#b6c2d0',
      textPrimary: '#0f172a',
      textSecondary: '#475569',
      textTertiary: '#64748b',
      accent: '#0d9488',
      accentOnAccent: '#ffffff',
      accentSubtle: 'rgba(13, 148, 136, 0.12)',
      accentMuted: 'rgba(13, 148, 136, 0.06)',
      statusRecommend: '#0f766e',
      statusWarn: '#b45309',
      statusAlert: '#b91c1c',
      statusNeutral: '#64748b',
      shadow1: 'none',
      shadow2: '0 10px 28px rgba(15, 23, 42, 0.08)',
      shadow3: '0 18px 44px rgba(15, 23, 42, 0.12)',
      fontBody: '"Inter", system-ui, sans-serif',
      fontDisplay: '"Inter", system-ui, sans-serif',
      fontMono: '"Inter", ui-monospace, monospace',
    },
  },
  'cozy-archive': {
    label: 'Cozy Archive',
    tokens: {
      pageBg: '#f5efe6',
      surfaceElevated: '#fffaf3',
      surfaceSunken: '#ede1d2',
      borderSubtle: '#d5c4af',
      borderStrong: '#b9a891',
      textPrimary: '#2c241e',
      textSecondary: '#6c5f56',
      textTertiary: '#8e7f76',
      accent: '#0d9488',
      accentOnAccent: '#ffffff',
      accentSubtle: 'rgba(13, 148, 136, 0.12)',
      accentMuted: 'rgba(13, 148, 136, 0.05)',
      statusRecommend: '#117a70',
      statusWarn: '#b97a2d',
      statusAlert: '#b0574a',
      statusNeutral: '#8b7f75',
      shadow1: 'none',
      shadow2: '0 10px 30px rgba(44, 36, 30, 0.08)',
      shadow3: '0 20px 46px rgba(44, 36, 30, 0.14)',
      fontBody: '"Instrument Serif", Georgia, serif',
      fontDisplay: '"Instrument Serif", Georgia, serif',
      fontMono: '"Inter", ui-monospace, monospace',
    },
  },
  'botanical-press': {
    label: 'Botanical Press',
    tokens: {
      pageBg: '#ede5dc',
      surfaceElevated: '#f7f2ee',
      surfaceSunken: '#e2d5cb',
      borderSubtle: '#c0af99',
      borderStrong: '#b2babc',
      textPrimary: '#3a302a',
      textSecondary: '#7a6e68',
      textTertiary: '#a39a94',
      accent: '#b57873',
      accentOnAccent: '#ffffff',
      accentSubtle: 'rgba(181, 120, 115, 0.1)',
      accentMuted: 'rgba(181, 120, 115, 0.05)',
      statusRecommend: '#8fa68c',
      statusWarn: '#c9a87c',
      statusAlert: '#b57873',
      statusNeutral: '#b2babc',
      shadow1: 'none',
      shadow2: 'none',
      shadow3: '0 8px 28px rgba(58, 48, 42, 0.1)',
      fontBody: '"DM Sans", "Inter", system-ui, sans-serif',
      fontDisplay: '"IM Fell DW Pica", "Instrument Serif", Georgia, serif',
      fontMono: '"DM Sans", "Inter", ui-monospace, monospace',
    },
  },
}

export function isThemeName(value: string): value is ThemeName {
  return value in themeRegistry
}
