// <auto-generated />
using System;
using Librory.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Librory.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LibroryDbContext))]
    partial class LibroryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("librory")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Librory.Domain.Models.BookCopy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookEditionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Condition")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("DuplicateStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid");

                    b.Property<string>("IntakeNotes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("PurchasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("PurchaseStore")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("PurchasedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ShelfLocation")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("BookEditionId");

                    b.HasIndex("FamilyId");

                    b.HasIndex("MemberId");

                    b.ToTable("book_copies", "librory");
                });

            modelBuilder.Entity("Librory.Domain.Models.BookEdition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookWorkId")
                        .HasColumnType("uuid");

                    b.Property<string>("Format")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Isbn")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int?>("PublicationYear")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BookWorkId");

                    b.ToTable("book_editions", "librory");
                });

            modelBuilder.Entity("Librory.Domain.Models.BookRecognitionJob", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Language")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("ResultJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("SourcePhotoPath")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId", "CreatedAt");

                    b.HasIndex("FamilyId", "Status");

                    b.ToTable("book_recognition_jobs", "librory");
                });

            modelBuilder.Entity("Librory.Domain.Models.BookWork", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CanonicalAuthor")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("CanonicalTitle")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.ToTable("book_works", "librory");
                });

            modelBuilder.Entity("Librory.Domain.Models.Family", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("families", "librory");
                });

            modelBuilder.Entity("Librory.Domain.Models.FamilyInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AcceptedAccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByMemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RevokedByMemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("SupersededByInvitationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TargetMemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("AcceptedAccountId");

                    b.HasIndex("CreatedByMemberId");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("RevokedByMemberId");

                    b.HasIndex("TargetMemberId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("FamilyId", "Email", "Status");

                    b.ToTable("family_invitations", "librory");
                });

            modelBuilder.Entity("Librory.Domain.Models.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("UserAccountId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserAccountId");

                    b.HasIndex("FamilyId", "DisplayName")
                        .IsUnique();

                    b.ToTable("members", "librory");
                });

            modelBuilder.Entity("Librory.Domain.Models.RecommendationProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ExcludedAuthors")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExcludedGenres")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExcludedStyles")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FavoriteAuthors")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FavoriteGenres")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FavoriteStyles")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("MaximumAge")
                        .HasColumnType("integer");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<int?>("MinimumAge")
                        .HasColumnType("integer");

                    b.Property<string>("PreferenceNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("PreferredBookLanguages")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfileVisibility")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("UseInFamilyRecommendations")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("MemberId")
                        .IsUnique();

                    b.ToTable("recommendation_profiles", "librory");
                });

            modelBuilder.Entity("Librory.Domain.Models.ScanCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Author")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("ConfidenceLabel")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("DetectedLanguage")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("DisplayTitle")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("DuplicateMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsAlreadyOwned")
                        .HasColumnType("boolean");

                    b.Property<decimal>("RecommendationScore")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<Guid>("ScanSessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ScanSessionId");

                    b.ToTable("scan_candidates", "librory");
                });

            modelBuilder.Entity("Librory.Domain.Models.ScanSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid");

                    b.Property<bool>("HasMixedLanguages")
                        .HasColumnType("boolean");

                    b.Property<string>("InferredLanguage")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ShelfPhotoPath")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<Guid?>("TargetMemberId")
                        .HasColumnType("uuid");

                    b.Property<bool>("TargetProfileAvailable")
                        .HasColumnType("boolean");

                    b.Property<bool>("TargetProfileUsed")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("TargetMemberId");

                    b.HasIndex("FamilyId", "CreatedAt");

                    b.HasIndex("FamilyId", "TargetMemberId");

                    b.ToTable("scan_sessions", "librory");
                });

            modelBuilder.Entity("Librory.Domain.Models.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("user_accounts", "librory");
                });

            modelBuilder.Entity("Librory.Domain.Models.WishlistItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Author")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid?>("BookEditionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BookWorkId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("BookEditionId");

                    b.HasIndex("BookWorkId");

                    b.HasIndex("FamilyId");

                    b.ToTable("wishlist_items", "librory");
                });

            modelBuilder.Entity("Librory.Domain.Models.BookCopy", b =>
                {
                    b.HasOne("Librory.Domain.Models.BookEdition", "BookEdition")
                        .WithMany()
                        .HasForeignKey("BookEditionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Librory.Domain.Models.Family", "Family")
                        .WithMany("BookCopies")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Librory.Domain.Models.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BookEdition");

                    b.Navigation("Family");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Librory.Domain.Models.BookEdition", b =>
                {
                    b.HasOne("Librory.Domain.Models.BookWork", "BookWork")
                        .WithMany("Editions")
                        .HasForeignKey("BookWorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Librory.Domain.Models.MetadataProvenance", "PublicationYearProvenance", b1 =>
                        {
                            b1.Property<Guid>("BookEditionId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("CapturedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("publication_year_captured_at");

                            b1.Property<decimal?>("Confidence")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("publication_year_confidence");

                            b1.Property<bool>("Exists")
                                .HasColumnType("boolean")
                                .HasColumnName("publication_year_provenance_exists");

                            b1.Property<string>("Source")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("publication_year_source");

                            b1.Property<string>("SourceId")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("publication_year_source_id");

                            b1.HasKey("BookEditionId");

                            b1.ToTable("book_editions", "librory");

                            b1.WithOwner()
                                .HasForeignKey("BookEditionId");
                        });

                    b.OwnsOne("Librory.Domain.Models.LocalizedText", "Subtitle", b1 =>
                        {
                            b1.Property<Guid>("BookEditionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Chinese")
                                .HasMaxLength(4000)
                                .HasColumnType("character varying(4000)")
                                .HasColumnName("subtitle_chinese");

                            b1.Property<string>("English")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("character varying(4000)")
                                .HasColumnName("subtitle_english");

                            b1.HasKey("BookEditionId");

                            b1.ToTable("book_editions", "librory");

                            b1.WithOwner()
                                .HasForeignKey("BookEditionId");
                        });

                    b.OwnsOne("Librory.Domain.Models.MetadataProvenance", "SubtitleProvenance", b1 =>
                        {
                            b1.Property<Guid>("BookEditionId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("CapturedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("subtitle_captured_at");

                            b1.Property<decimal?>("Confidence")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("subtitle_confidence");

                            b1.Property<bool>("Exists")
                                .HasColumnType("boolean")
                                .HasColumnName("subtitle_provenance_exists");

                            b1.Property<string>("Source")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("subtitle_source");

                            b1.Property<string>("SourceId")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("subtitle_source_id");

                            b1.HasKey("BookEditionId");

                            b1.ToTable("book_editions", "librory");

                            b1.WithOwner()
                                .HasForeignKey("BookEditionId");
                        });

                    b.Navigation("BookWork");

                    b.Navigation("PublicationYearProvenance");

                    b.Navigation("Subtitle");

                    b.Navigation("SubtitleProvenance");
                });

            modelBuilder.Entity("Librory.Domain.Models.BookRecognitionJob", b =>
                {
                    b.HasOne("Librory.Domain.Models.Family", "Family")
                        .WithMany()
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Family");
                });

            modelBuilder.Entity("Librory.Domain.Models.BookWork", b =>
                {
                    b.OwnsOne("Librory.Domain.Models.MetadataProvenance", "CanonicalAuthorProvenance", b1 =>
                        {
                            b1.Property<Guid>("BookWorkId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("CapturedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("canonical_author_captured_at");

                            b1.Property<decimal?>("Confidence")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("canonical_author_confidence");

                            b1.Property<bool>("Exists")
                                .HasColumnType("boolean")
                                .HasColumnName("canonical_author_provenance_exists");

                            b1.Property<string>("Source")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("canonical_author_source");

                            b1.Property<string>("SourceId")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("canonical_author_source_id");

                            b1.HasKey("BookWorkId");

                            b1.ToTable("book_works", "librory");

                            b1.WithOwner()
                                .HasForeignKey("BookWorkId");
                        });

                    b.OwnsOne("Librory.Domain.Models.LocalizedText", "Summary", b1 =>
                        {
                            b1.Property<Guid>("BookWorkId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Chinese")
                                .HasMaxLength(4000)
                                .HasColumnType("character varying(4000)")
                                .HasColumnName("summary_chinese");

                            b1.Property<string>("English")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("character varying(4000)")
                                .HasColumnName("summary_english");

                            b1.HasKey("BookWorkId");

                            b1.ToTable("book_works", "librory");

                            b1.WithOwner()
                                .HasForeignKey("BookWorkId");
                        });

                    b.OwnsOne("Librory.Domain.Models.MetadataProvenance", "SummaryProvenance", b1 =>
                        {
                            b1.Property<Guid>("BookWorkId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("CapturedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("summary_captured_at");

                            b1.Property<decimal?>("Confidence")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("summary_confidence");

                            b1.Property<bool>("Exists")
                                .HasColumnType("boolean")
                                .HasColumnName("summary_provenance_exists");

                            b1.Property<string>("Source")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("summary_source");

                            b1.Property<string>("SourceId")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("summary_source_id");

                            b1.HasKey("BookWorkId");

                            b1.ToTable("book_works", "librory");

                            b1.WithOwner()
                                .HasForeignKey("BookWorkId");
                        });

                    b.Navigation("CanonicalAuthorProvenance");

                    b.Navigation("Summary");

                    b.Navigation("SummaryProvenance");
                });

            modelBuilder.Entity("Librory.Domain.Models.FamilyInvitation", b =>
                {
                    b.HasOne("Librory.Domain.Models.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("AcceptedAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Librory.Domain.Models.Member", null)
                        .WithMany()
                        .HasForeignKey("CreatedByMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Librory.Domain.Models.Family", null)
                        .WithMany()
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Librory.Domain.Models.Member", null)
                        .WithMany()
                        .HasForeignKey("RevokedByMemberId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Librory.Domain.Models.Member", null)
                        .WithMany()
                        .HasForeignKey("TargetMemberId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Librory.Domain.Models.Member", b =>
                {
                    b.HasOne("Librory.Domain.Models.Family", "Family")
                        .WithMany("Members")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Librory.Domain.Models.UserAccount", "UserAccount")
                        .WithMany("Memberships")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Family");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("Librory.Domain.Models.RecommendationProfile", b =>
                {
                    b.HasOne("Librory.Domain.Models.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Librory.Domain.Models.ScanCandidate", b =>
                {
                    b.HasOne("Librory.Domain.Models.ScanSession", "ScanSession")
                        .WithMany("Candidates")
                        .HasForeignKey("ScanSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScanSession");
                });

            modelBuilder.Entity("Librory.Domain.Models.ScanSession", b =>
                {
                    b.HasOne("Librory.Domain.Models.Family", "Family")
                        .WithMany("ScanSessions")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Librory.Domain.Models.Member", null)
                        .WithMany()
                        .HasForeignKey("TargetMemberId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Family");
                });

            modelBuilder.Entity("Librory.Domain.Models.UserAccount", b =>
                {
                    b.OwnsMany("Librory.Domain.Models.ExternalIdentity", "ExternalIdentities", b1 =>
                        {
                            b1.Property<Guid>("UserAccountId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Provider")
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)");

                            b1.Property<string>("ProviderSubject")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("DisplayName")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("Email")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)");

                            b1.Property<DateTimeOffset?>("LinkedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("UserAccountId", "Provider", "ProviderSubject");

                            b1.HasIndex("Provider", "ProviderSubject")
                                .IsUnique();

                            b1.ToTable("user_account_external_identities", "librory");

                            b1.WithOwner()
                                .HasForeignKey("UserAccountId");
                        });

                    b.Navigation("ExternalIdentities");
                });

            modelBuilder.Entity("Librory.Domain.Models.WishlistItem", b =>
                {
                    b.HasOne("Librory.Domain.Models.BookEdition", "BookEdition")
                        .WithMany()
                        .HasForeignKey("BookEditionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Librory.Domain.Models.BookWork", "BookWork")
                        .WithMany()
                        .HasForeignKey("BookWorkId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Librory.Domain.Models.Family", "Family")
                        .WithMany("WishlistItems")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookEdition");

                    b.Navigation("BookWork");

                    b.Navigation("Family");
                });

            modelBuilder.Entity("Librory.Domain.Models.BookWork", b =>
                {
                    b.Navigation("Editions");
                });

            modelBuilder.Entity("Librory.Domain.Models.Family", b =>
                {
                    b.Navigation("BookCopies");

                    b.Navigation("Members");

                    b.Navigation("ScanSessions");

                    b.Navigation("WishlistItems");
                });

            modelBuilder.Entity("Librory.Domain.Models.ScanSession", b =>
                {
                    b.Navigation("Candidates");
                });

            modelBuilder.Entity("Librory.Domain.Models.UserAccount", b =>
                {
                    b.Navigation("Memberships");
                });
#pragma warning restore 612, 618
        }
    }
}
